services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf
    restart: unless-stopped
    command: tunnel --no-autoupdate --metrics 0.0.0.0:2001 --url http://host.docker.internal:5000
    ports:
      - "2000:2000"
